### ISSUE TITLE
Can't compile with notify 5.0.0-pre.11

### ISSUE THREAD

**Issue by hobofan** [Canop/bacon#51]
Trying to install as per the readme (`cargo install bacon`) fails with:

```
error[E0599]: no function or associated item named `new_immediate` found for trait object `dyn Watcher` in the current scope
  --> /Users/max/.cargo/registry/src/github.com-1ecc6299db9ec823/bacon-1.1.7/src/app.rs:16:52
   |
16 |     let mut watcher: RecommendedWatcher = Watcher::new_immediate(move |res| match res {
   |                                                    ^^^^^^^^^^^^^ function or associated item not found in `dyn Watcher`
   ```
   
This is due to the newly released version `5.0.0-pre.11` of the `notify` crate which [removed the new_immediate constructor](https://github.com/notify-rs/notify/pull/336).

-----

Workaround for anyone who wants to install bacon right now:
- clone the repository
- install with `cargo install --path . --locked` (as that respects the Cargo.lock of the repository)

**Comment by Canop** [comment]
Sorry, coming back from holidays. Will look at this tomorrow.
